os: osx
osx_image: xcode8
language: r
cache: packages
sudo: required
r:
  - oldrel
  - release
  - devel
branches:
  only:
  - master
  - osx_build

before_install:
#  - brew tap caskroom/cask
#  - brew install brew-cask
#  - brew install Caskroom/cask/xquartz
#  - brew cask install mactex
  - brew install gsl@1
  
  
after_install:
   - cat /home/travis/build/adalisan/RGraphM/RGraphM.Rcheck/00install.log
